package frontend;

import backend.ProgramFunctions.CourseManagement.Course;
import backend.ProgramFunctions.LessonAndLearningFeatures.Lesson;
import backend.ProgramFunctions.StudentManagement.Student;
import backend.ProgramService.ProgramService;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * Fully Implemented "My Courses" Page for Students.
 * Shows enrolled courses, lessons, and progress.
 */
public class EnrollCoursesPage extends javax.swing.JFrame {

    private ProgramService service;
    private Student currentUser;

    private DefaultListModel<Course> coursesListModel;
    private DefaultListModel<Lesson> lessonsListModel;

    /**
     * Creates new form EnrollCoursesPage
     * @param service The single ProgramService instance
     * @param user The logged-in Student
     */
    public EnrollCoursesPage(ProgramService service, Student user) {
        initComponents();
        this.service = service;
        this.currentUser = user;
        this.setLocationRelativeTo(null); // Center window

        // Change window behavior to DISPOSE_ON_CLOSE
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);

        // Setup List Models
        coursesListModel = new DefaultListModel<>();
        coursesList.setModel(coursesListModel);

        lessonsListModel = new DefaultListModel<>();
        lessonsList.setModel(lessonsListModel);

        // Load the student's courses
        loadEnrolledCourses();
    }

    /**
     * Finds the courses the student is enrolled in and adds them to the list.
     */
    private void loadEnrolledCourses() {
        coursesListModel.clear();
        ArrayList<String> courseIds = currentUser.getEnrolledCourses();
        for (String courseId : courseIds) {
            Course course = service.findCourseById(courseId);
            if (course != null) {
                coursesListModel.addElement(course);
            }
        }
    }

    /**
     * Loads the lessons for a selected course into the lesson list.
     */
    private void loadLessonsForCourse(Course course) {
        lessonsListModel.clear();
        if (course != null) {
            for (Lesson lesson : course.getLessons()) {
                lessonsListModel.addElement(lesson);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursesList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lessonsList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lessonContentTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        markCompleteButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("My Courses & Progress");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("My Courses & Progress");

        jSplitPane1.setDividerLocation(200);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("My Courses");

        coursesList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        coursesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        coursesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                coursesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(coursesList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(0, 89, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Lessons");

        lessonsList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lessonsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lessonsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lessonsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lessonsList);

        lessonContentTextArea.setEditable(false);
        lessonContentTextArea.setColumns(20);
        lessonContentTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lessonContentTextArea.setLineWrap(true);
        lessonContentTextArea.setRows(5);
        lessonContentTextArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(lessonContentTextArea);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Lesson Content");

        markCompleteButton.setBackground(new java.awt.Color(0, 153, 204));
        markCompleteButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        markCompleteButton.setForeground(new java.awt.Color(5, 3, 3));
        markCompleteButton.setText("Mark as Complete");
        markCompleteButton.setEnabled(false);
        markCompleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markCompleteButtonActionPerformed(evt);
            }
        });

        statusLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(0, 153, 51));
        statusLabel.setText("Status: -");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(markCompleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(markCompleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(statusLabel))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSplitPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jSplitPane1)
                                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>

    /**
     * Event handler for when a student clicks on a course in the list.
     * It populates the lessons list.
     */
    private void coursesListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (!evt.getValueIsAdjusting()) {
            Course selectedCourse = coursesList.getSelectedValue();
            if (selectedCourse != null) {
                loadLessonsForCourse(selectedCourse);
            } else {
                lessonsListModel.clear();
            }
            // Clear details when course selection changes
            lessonContentTextArea.setText("");
            statusLabel.setText("Status: -");
            markCompleteButton.setEnabled(false);
        }
    }

    /**
     * Event handler for when a student clicks on a lesson.
     * It displays the lesson content and checks its completion status.
     */
    private void lessonsListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (!evt.getValueIsAdjusting()) {
            Lesson selectedLesson = lessonsList.getSelectedValue();
            Course selectedCourse = coursesList.getSelectedValue();

            if (selectedLesson != null && selectedCourse != null) {
                // Display lesson content
                lessonContentTextArea.setText(selectedLesson.getContent());

                // Check if the lesson is already complete
                boolean isComplete = currentUser.isLessonComplete(selectedCourse.getCourseId(), selectedLesson.getLessonId());

                if (isComplete) {
                    statusLabel.setText("Status: Completed");
                    statusLabel.setForeground(new java.awt.Color(0, 153, 51)); // Green
                    markCompleteButton.setEnabled(false); // Can't mark again
                } else {
                    statusLabel.setText("Status: Incomplete");
                    statusLabel.setForeground(new java.awt.Color(204, 0, 0)); // Red
                    markCompleteButton.setEnabled(true); // Allow marking
                }
            } else {
                // Clear details if no lesson is selected
                lessonContentTextArea.setText("");
                statusLabel.setText("Status: -");
                markCompleteButton.setEnabled(false);
            }
        }
    }

    /**
     * Event handler for the "Mark as Complete" button.
     */
    private void markCompleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        Lesson selectedLesson = lessonsList.getSelectedValue();
        Course selectedCourse = coursesList.getSelectedValue();

        if (selectedLesson != null && selectedCourse != null) {
            // Use the service to mark as complete (and save)
            service.markLessonComplete(currentUser, selectedCourse.getCourseId(), selectedLesson.getLessonId());
            JOptionPane.showMessageDialog(this, "Lesson marked as complete!");

            // Refresh status display
            statusLabel.setText("Status: Completed");
            statusLabel.setForeground(new java.awt.Color(0, 153, 51));
            markCompleteButton.setEnabled(false);
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JList<Course> coursesList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea lessonContentTextArea;
    private javax.swing.JList<Lesson> lessonsList;
    private javax.swing.JButton markCompleteButton;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration
}