/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.ProgramFunctions.InstructorManagement.Instructor;
import backend.ProgramFunctions.UserAccountManagement.User;
import backend.ProgramService.ProgramService;

/**
 *
 * @author ahmme
 */
public class Instructorhomepage extends javax.swing.JFrame {

    private ProgramService service;
    private Instructor currentUser;
    /**
     * Creates new form Instructorhomepage
     */

    public Instructorhomepage(ProgramService service, User user) {
        initComponents();
        this.service = service;
        this.currentUser = (Instructor) user; // Cast and store
        this.setLocationRelativeTo(null); // Center window

        // Personalize the welcome message
        jLabel2.setText("Welcome, " + currentUser.getUsername() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ManageCoursesButton = new javax.swing.JButton();
        CreateCoursesButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Welcome!");

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("Choose your operation:");

        ManageCoursesButton.setBackground(new java.awt.Color(255, 255, 0));
        ManageCoursesButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        ManageCoursesButton.setForeground(new java.awt.Color(255, 51, 0));
        ManageCoursesButton.setText("Manage courses");
        ManageCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCoursesButtonActionPerformed(evt);
            }
        });

        CreateCoursesButton1.setBackground(new java.awt.Color(255, 255, 0));
        CreateCoursesButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CreateCoursesButton1.setForeground(new java.awt.Color(255, 51, 0));
        CreateCoursesButton1.setText("Create courses.");
        CreateCoursesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateCoursesButton1ActionPerformed(evt);
            }
        });

        LogoutButton.setBackground(new java.awt.Color(0, 0, 0));
        LogoutButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ManageCoursesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateCoursesButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(CreateCoursesButton1)
                .addGap(27, 27, 27)
                .addComponent(ManageCoursesButton)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ManageCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageCoursesButtonActionPerformed
        new MangeCoursesPage(service,currentUser).setVisible(true);
    //this.dispose();
    }//GEN-LAST:event_ManageCoursesButtonActionPerformed

    private void CreateCoursesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateCoursesButton1ActionPerformed
    new CreateCoursesPage(service, currentUser).setVisible(true);
    //this.dispose();
    }//GEN-LAST:event_CreateCoursesButton1ActionPerformed
    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Go back to Login screen
        new Login(service).setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateCoursesButton1;
    private javax.swing.JButton ManageCoursesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton LogoutButton;
    // End of variables declaration//GEN-END:variables
}
