package frontend;

import backend.ProgramFunctions.CourseManagement.Course;
import backend.ProgramFunctions.InstructorManagement.Instructor;
import backend.ProgramFunctions.LessonAndLearningFeatures.Lesson;
import backend.ProgramService.ProgramService;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;


//manage the course allow to edit delete lessons for the existing courses that has been created
public class MangeCoursesPage extends javax.swing.JFrame {

    private ProgramService service;
    private Instructor currentUser;

    private DefaultListModel<Course> coursesListModel;
    private DefaultListModel<Lesson> lessonsListModel;

    private Course selectedCourse = null;
    private Lesson selectedLesson = null;

    /**
     * Creates new form MangeCoursePage
     * @param service The single ProgramService instance
     * @param user The logged-in Instructor
     */
    public MangeCoursesPage(ProgramService service, Instructor user) {
        initComponents();
        this.service = service;
        this.currentUser = user;
        this.setLocationRelativeTo(null); // Center window

        // Change window behavior to DISPOSE_ON_CLOSE
        setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);

        // Setup List Models
        coursesListModel = new DefaultListModel<>();
        coursesList.setModel(coursesListModel);

        lessonsListModel = new DefaultListModel<>();
        lessonsList.setModel(lessonsListModel);

        // Load the instructor's courses
        loadCreatedCourses();
    }

    /**
     * Finds the courses created by this instructor and adds them to the list.
     */
    private void loadCreatedCourses() {
        coursesListModel.clear();
        ArrayList<String> courseIds = currentUser.getCreatedCourses();
        for (String courseId : courseIds) {
            Course course = service.findCourseById(courseId);
            if (course != null) {
                coursesListModel.addElement(course);
            }
        }
    }

    /**
     * Loads the lessons for a selected course into the lesson list.
     */
    private void loadLessonsForCourse(Course course) {
        lessonsListModel.clear();
        if (course != null) {
            for (Lesson lesson : course.getLessons()) {
                lessonsListModel.addElement(lesson);
            }
        }
    }

    /**
     * Clears the lesson editor form and resets button states.
     */
    private void clearLessonForm() {
        lessonTitleField.setText("");
        lessonContentTextArea.setText("");
        selectedLesson = null;
        lessonsList.clearSelection();
        saveLessonButton.setText("Save New Lesson");
        deleteLessonButton.setEnabled(false);
        // Only enable saving a new lesson if a course is selected
        saveLessonButton.setEnabled(selectedCourse != null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursesList = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lessonsList = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lessonTitleField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lessonContentTextArea = new javax.swing.JTextArea();
        saveLessonButton = new javax.swing.JButton();
        deleteLessonButton = new javax.swing.JButton();
        clearLessonFormButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage My Courses");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Manage My Courses");

        jSplitPane1.setDividerLocation(220);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("My Courses");

        coursesList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        coursesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        coursesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                coursesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(coursesList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(0, 109, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Lessons");

        lessonsList.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lessonsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lessonsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lessonsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lessonsList);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lesson Editor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Lesson Title:");

        lessonTitleField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Lesson Content:");

        lessonContentTextArea.setColumns(20);
        lessonContentTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lessonContentTextArea.setLineWrap(true);
        lessonContentTextArea.setRows(5);
        lessonContentTextArea.setWrapStyleWord(true);
        jScrollPane3.setViewportView(lessonContentTextArea);

        saveLessonButton.setBackground(new java.awt.Color(0, 153, 51));
        saveLessonButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveLessonButton.setForeground(new java.awt.Color(0, 0, 0));
        saveLessonButton.setText("Save New Lesson");
        saveLessonButton.setEnabled(false);
        saveLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLessonButtonActionPerformed(evt);
            }
        });

        deleteLessonButton.setBackground(new java.awt.Color(204, 0, 0));
        deleteLessonButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteLessonButton.setForeground(new java.awt.Color(5, 3, 3));
        deleteLessonButton.setText("Delete Lesson");
        deleteLessonButton.setEnabled(false);
        deleteLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLessonButtonActionPerformed(evt);
            }
        });

        clearLessonFormButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearLessonFormButton.setText("Clear Form (New)");
        clearLessonFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLessonFormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lessonTitleField)
                                        .addComponent(jScrollPane3)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addComponent(clearLessonFormButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                                .addComponent(deleteLessonButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(saveLessonButton)))
                                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lessonTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(saveLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(clearLessonFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSplitPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jSplitPane1)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    /**
     * Event handler for when an instructor clicks on a course in the list.
     * It populates the lessons list for that course.
     */
    private void coursesListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (!evt.getValueIsAdjusting()) {
            selectedCourse = coursesList.getSelectedValue();
            if (selectedCourse != null) {
                loadLessonsForCourse(selectedCourse);
                saveLessonButton.setEnabled(true); // Enable saving new lessons
            } else {
                lessonsListModel.clear();
                saveLessonButton.setEnabled(false); // Disable if no course is selected
            }
            clearLessonForm(); // Clear form when course selection changes
        }
    }

    /**
     * Event handler for when an instructor clicks on a lesson.
     * It loads the lesson's data into the editor form.
     */
    private void lessonsListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        if (!evt.getValueIsAdjusting()) {
            selectedLesson = lessonsList.getSelectedValue();
            if (selectedLesson != null) {
                // Load lesson data into editor
                lessonTitleField.setText(selectedLesson.getTitle());
                lessonContentTextArea.setText(selectedLesson.getContent());

                // Update button states for editing
                saveLessonButton.setText("Save Edits");
                deleteLessonButton.setEnabled(true);
            }
        }
    }

    /**
     * Event handler for the "Save" button.
     * It either creates a new lesson or updates an existing one.
     */
    private void saveLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedCourse == null) {
            JOptionPane.showMessageDialog(this, "Please select a course first.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String title = lessonTitleField.getText().trim();
        String content = lessonContentTextArea.getText().trim();

        if (title.isEmpty() || content.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Title and Content cannot be empty.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (selectedLesson == null) {
            // This is a NEW lesson
            Lesson newLesson = service.addLessonToCourse(selectedCourse, title, content);
            if (newLesson != null) {
                JOptionPane.showMessageDialog(this, "Lesson '" + newLesson.getTitle() + "' added.");
            }
        } else {
            // We are EDITING an existing lesson
            service.updateLesson(selectedLesson, title, content);
            JOptionPane.showMessageDialog(this, "Lesson '" + selectedLesson.getTitle() + "' updated.");
        }

        // Refresh and clear
        loadLessonsForCourse(selectedCourse);
        clearLessonForm();
    }

    /**
     * Event handler for the "Delete" button.
     */
    private void deleteLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (selectedLesson == null || selectedCourse == null) {
            return; // Should be impossible if button is enabled, but good practice
        }

        int choice = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete the lesson '" + selectedLesson.getTitle() + "'?",
                "Confirm Deletion", JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            service.deleteLesson(selectedCourse, selectedLesson);
            JOptionPane.showMessageDialog(this, "Lesson deleted.");
            loadLessonsForCourse(selectedCourse);
            clearLessonForm();
        }
    }

    /**
     * Event handler for the "Clear Form" button.
     * Resets the editor to create a new lesson.
     */
    private void clearLessonFormButtonActionPerformed(java.awt.event.ActionEvent evt) {
        clearLessonForm();
    }


    // Variables declaration - do not modify
    private javax.swing.JButton clearLessonFormButton;
    private javax.swing.JList<Course> coursesList;
    private javax.swing.JButton deleteLessonButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea lessonContentTextArea;
    private javax.swing.JTextField lessonTitleField;
    private javax.swing.JList<Lesson> lessonsList;
    private javax.swing.JButton saveLessonButton;
    // End of variables declaration                   
}