/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.ProgramService.ProgramService;
import backend.ProgramFunctions.UserAccountManagement.User;
import backend.ProgramFunctions.StudentManagement.Student; // Import Student

import java.awt.*;

/**
 *
 * @author ahmme
 */
public class Studenthomepage extends javax.swing.JFrame {
    private ProgramService service;
    private Student currentUser;
    /**
     * Creates new form Studenthomepage
     */

    public Studenthomepage(ProgramService service, User user) {
        initComponents();
        this.service = service;
        this.currentUser = (Student) user; // Cast and store
        this.setLocationRelativeTo(null); // Center window

        // Personalize the welcome message
        jLabel2.setText("Welcome, " + currentUser.getUsername() + "!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

         jLabel1 = new javax.swing.JLabel();
         jLabel2 = new javax.swing.JLabel();
         BrowseCoursesButton = new javax.swing.JButton();
         EnrollCoursesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setText("Choose your operation:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", Font.BOLD, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Welcome!");

        BrowseCoursesButton.setBackground(new java.awt.Color(255, 255, 0));
        BrowseCoursesButton.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 24)); // NOI18N
        BrowseCoursesButton.setForeground(new java.awt.Color(255, 51, 0));
        BrowseCoursesButton.setText("Browse courses");
        BrowseCoursesButton.addActionListener(this::BrowseCoursesButtonActionPerformed);

        EnrollCoursesButton.setBackground(new java.awt.Color(255, 255, 0));
        EnrollCoursesButton.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 24)); // NOI18N
        EnrollCoursesButton.setForeground(new java.awt.Color(255, 51, 0));
        EnrollCoursesButton.setText("Enroll courses");
        EnrollCoursesButton.addActionListener(this::EnrollCoursesButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BrowseCoursesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EnrollCoursesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(BrowseCoursesButton)
                .addGap(38, 38, 38)
                .addComponent(EnrollCoursesButton)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void BrowseCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {
    new BrowseCoursesPage().setVisible(true);

    }

    private void EnrollCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {
    new EnrollCoursesPage(service, currentUser).setVisible(true);

    }
    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Go back to Login screen
        new Login(service).setVisible(true);
        this.dispose();
    }
    /**
     * @param args the command line arguments
     */
    private javax.swing.JButton BrowseCoursesButton;
    private javax.swing.JButton EnrollCoursesButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
}