/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import backend.ProgramFunctions.CourseManagement.Course;
import backend.ProgramFunctions.StudentManagement.Student;

import java.util.ArrayList;
import backend.JsonDatabaseManager.CourseDatabaseManager;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ahmme
 */
public class BrowseCoursesPage extends javax.swing.JFrame {

    private ProgramService service; //create a class that controls the data base
    private Student currentUser;

public BrowseCoursesPage() {
    initComponents();
    this.service =service;
    this.currentUser = currentUser;
    this.setLocationRelativeTo(null);//to make the window in the center
}
    // ===============================================
    // Load courses from JSON and fill table
    // ===============================================
    private void loadCoursesIntoTable() {
    //private method only accessible within the class
    //fetching all the data from using the service object which has the blueprint of Programsevice
      ArrayList<Course> courses = service.getAllCoures();

        DefaultTableModel model = (DefaultTableModel) CoursesTable.getModel();
        model.setRowCount(0); // Clear old rows to prevetnt duplication

        for (Course c : courses) {
            if (service.findUserById(c.getInstructorId()) != null) {
                // If the user exists, get their username to display in the table
                instructorName = service.findUserById(c.getInstructorId()).getUsername();

            }
            String status = currentUser.isEnrolled(c.getCourseId()) ? "Enrolled" : "Not Enrolled"; // ternary statement condition? value if t: value if false

            model.addRow(new Object[]{
                c.getCourseId(),
                c.getCourseName(),
                c.getInstructorName(),
                c.getDescription()
            });
        }
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CoursesTable = new javax.swing.JTable();
        EnrollButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        // IMPORTANT: Set to dispose, not exit
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Browse All Courses");

        CoursesTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CoursesTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Course ID", "Title", "Instructor", "Description", "Status"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CoursesTable.setRowHeight(25);
        CoursesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(CoursesTable);

        EnrollButton.setBackground(new java.awt.Color(51, 204, 0));
        EnrollButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        EnrollButton.setForeground(new java.awt.Color(4, 3, 3));
        EnrollButton.setText("Enroll in Selected Course");
        EnrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("All Available Courses");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(EnrollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(EnrollButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }

        /* Create and display the form */

    private void EnrollButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow =CoursesTable.getSelectedRow();
        if(selectedRow == -1 ){
            JOptionPane.showMessageDialog(this, "Please select a course from the table first.");
            return;
        }// if no rows are selected
        String courseId = (String) CoursesTable.getValueAt(selectedRow, 0);
        Course courseToEnroll = service.findCourseById(courseId);
        if (courseToEnroll == null) {
            JOptionPane.showMessageDialog(this, "Error: Selected course not found.");
            return;
            if (currentUser.isEnrolled(courseId)) {
                JOptionPane.showMessageDialog(this, "You are already enrolled in this course.");
                return;  //check if already enrolled
            }
            boolean success = service.enrollStudentInCourse(currentUser, courseToEnroll);

            if (success) {
                JOptionPane.showMessageDialog(this, "Successfully enrolled in " + courseToEnroll.getTitle() + "!");
                // Refresh the table to show "Enrolled" status
                loadCoursesIntoTable();
            }
            else {
                JOptionPane.showMessageDialog(this, "Enrollment failed.");
            }

            }
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CoursesTable;
    private javax.swing.JButton EnrollButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
